= Icinga SNMP Image
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Asciidoctor_: https://asciidoctor.org/[Asciidoctor]
:Buildah: https://buildah.io/[Buildah]
:check_interfaces: https://github.com/NETWAYS/check_interfaces[check_interfaces]
:Icinga: https://icinga.com/[Icinga]
:Icinga-2-Docker-Image: https://github.com/Icinga/docker-icinga2[Icinga 2 - Docker Image]
:Manubulon-SNMP-Plugins: https://github.com/SteScho/manubulon-snmp[Manubulon SNMP Plugins]
:Linux: https://www.linuxfoundation.org/[Linux]
:Podman: https://podman.io/[Podman]
:pre-commit: https://pre-commit.com/[pre-commit]

image:https://github.com/jwillikers/icinga-snmp-image/workflows/Build/badge.svg["Build Status", link="https://github.com/jwillikers/icinga-snmp-image/actions?query=workflow%3ABuild"]

A container image based off of the official {Icinga-2-Docker-Image} which includes various SNMP plugins.
These include the {Manubulon-SNMP-plugins}, the https://github.com/alexander-naumov/openbsd_snmp3_check[OpenBSD SNMPv3 Check], and the {check_interfaces} plugins.

== Synopsis

Image:: https://quay.io/repository/jwillikers/icinga-snmp[quay.io/jwillikers/icinga-snmp]

Tags::
* `latest`

Supported architectures::
* `amd64` _(x86_64)_
* `arm64` _(aarch64)_

Labels::
`io.containers.autoupdate=registry`::: Enables automatic updates when using {Podman} and the _fully-qualified_ image name.

Contains a patched version of `/usr/share/perl5/Net/SNMP/Security/USM.pm` to support newer versions of the SHA algorithms for authentication.

== Quick Start

Use this container image the same way as the {Icinga-2-Docker-Image}.
It just contains several SNMP plugins in addition to everything else in the official upstream image.
An example Kubernetes YAML configuration for running this container is available in my https://github.com/jwillikers/home-lab-helm[Home Lab Helm project].

== Build

. Install an implementation of Nix, such as https://lix.systems[Lix] used here.
+
[,sh]
----
curl -sSf -L https://install.lix.systems/lix | sh -s -- install
----

. Clone this repository.
+
[,sh]
----
git clone git@github.com:jwillikers/icinga-snmp-image.git
----

. Change into the project directory.
+
[,sh]
----
cd icinga-snmp-image
----

. Build the image.
+
[,sh]
----
nix build '.#icinga-snmp-image'
----

== Develop

For local development, `direnv` is recommended.
Follow these steps to install and enable it.

. Install direnv for your system according to the https://direnv.net/docs/installation.html[direnv installation instructions].
+
[,sh]
----
sudo rpm-ostree install direnv
sudo systemctl reboot
----

. Integrate direnv with your shell by following the instructions on the https://direnv.net/docs/hook.html[direnv Setup page].

. Permit the direnv configuration in the repository.
+
[,sh]
----
direnv allow
----

== Contributing

Contributions in the form of issues, feedback, and even pull requests are welcome.
Make sure to adhere to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== Open Source Software

This project is built on the hard work of countless open source contributors.
Several of these projects are enumerated below.

* {Asciidoctor_}
* {Buildah}
* {check_interfaces}
* {Icinga}
* {Linux}
* {Manubulon-SNMP-Plugins}
* {Podman}

== Code of Conduct

Refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct] for details.

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3], a copy of which is provided in the link:LICENSE.adoc[license file].

© 2023-2024 Jordan Williams

== Authors

mailto:{email}[{author}]
