{ buildGoModule, fetchFromGitHub }:
buildGoModule rec {
  pname = "icinga-container-entrypoint";
  version = "0-unstable-2024-07-09";

  src = fetchFromGitHub {
    owner = "Icinga";
    repo = "docker-icinga2";
    rev = "031401768d8fbaa1f42081a774d70d9f5d172a3c";
    sha256 = "sha256-bFEbTWDyJnzBn0T8vfEqlMumZi0gVpYj3jBzUs8gGJo=";
  };
  patches = [
    # Without this, we get error messages like:
    # vendor/golang.org/x/sys/unix/mremap.go:41:10: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
    # The patch was generated by changing "go 1.16" to "go 1.21" and executing `go mod tidy`.
    ./0001-Update-go-version-in-go.mod.patch
  ];
  sourceRoot = "${src.name}/entrypoint";

  vendorHash = "sha256-Trqxo8UNfZf5wrfHfIko4vLG/GmgsEXLBMk4NlzL3vM=";

  meta = {
    mainProgram = "entrypoint";
  };
}
